### ISSUE TITLE
Add ability to have dictionaries for words of a specific character 

### ISSUE THREAD

**Issue by wafis** [Miodec/monkeytype#158]
Would be cool if a user wanted to train a specific character, so I'm proposing having the option for a user to select a character they want to improve, and the prompt would have words that always contain that character. 

Example:
user would select the letter 'C' and all the words in the prompt would have the letter C.

**Comment by wafis** [comment]
I could see this being relatively easy to add, but as far as user experience goes does anyone have any suggestions?

**Comment by colord** [comment]
I think this would helpful if it was combined with #44 

The user goes to the custom test and underneath the 'custom' text next to 'change' is a 'practice' option. The practice option has two features (after the user does a time, word, or quote test AND has about 10 or so typos): 
1. Practice mistyped words.
2. Choose specific character(s) to practice with. This test would be similar to the words test with a number of words option (10, 25, 50, etc). The words would be taken from the language chosen. So if I chose language, 'english expanded' and I wanted words with 'c', it would build a subset of that word list.

**Comment by TheChaddestDave** [comment]
I personally think that some kind of functional dictionary with a search bar would be good, good but not amazing since google exists. Far more useful would be stuff local to the person's typing. 

For example, as mentioned, idea #44 that would give you a list of your most mistyped words. To expand upon this, a list of the slowest typed words would also be pretty useful.

**Comment by Miodec** [comment]
Implemented with words filter. Head to custom mode > change > word filter to filter a language of your choosing.
