### ISSUE TITLE
EMAlL login not persistent

### ISSUE THREAD

**Issue by Pinche-Dev** [Miodec/monkeytype#2189]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Current Behavior

you have to login every time even if you have turned ON "remember me" every time you close your browser

### Expected Behavior

you should not have to enter credintials every time you open monkeytype.com 

### Environment

- OS:Windows 10
- Browser: Edge (latest)
- Browser Version:

### Did you check incognito mode?

- [X] I have checked incognito mode

**Comment by Miodec** [comment]
Im pretty sure this could be some sort of privacy extension or something simmilar as nobody else is experiencing this. Please test again. Try different browsers.

**Comment by b3nj5m1n** [comment]
I get the same issue using Linux & Firefox.

Happens every time I restart my browser, and sometimes randomly when opening the website in a new tab.

Sometimes, the navbar then partially vanishes:
![2021-12-19_13-12](https://user-images.githubusercontent.com/47924309/146674476-2936da08-a99b-4894-80b0-eb7ba8e11815.png)
The buttons are still there, and I can click them, they're just invisible. Simply reloading doesn't help, I have to bypass the cache for the icons to appear again.

This is especially annoying because monkeytype is the only website where my password manager doesn't auto-fill the correct fields, so I have to manually copy/paste my email & password every time.

I do have 2 privacy extensions active, uBlock Origin & Chameleon. I suspect the latter one is probably causing the issue.

**Comment by Miodec** [comment]
Have you tested without any extensions running?

**Comment by b3nj5m1n** [comment]
Haven't gotten around to it yet, no.

**Comment by Miodec** [comment]
Any update?

**Comment by b3nj5m1n** [comment]
I'm no longer experiencing this issue on every restart of the browser, it seems to happen completely at random now, though less frequently. It also appears that when chameleon is running, I get the bug where the icons disappear, so I've just whitelisted monkeytype for now.

Sorry I couldn't be more helpful.

**Comment by Miodec** [comment]
Is it still happening after whitelisting it in chameleon?

**Comment by b3nj5m1n** [comment]
As I said, it's happening less frequently, but it has happened once or twice since. It also didn't start to occur more frequently or on startup when I removed monkeytype from the whitelist, so I believe chameleon has nothing to do with the login issue.

**Comment by Miodec** [comment]
I don't know, it has to be something specific to your network because noone else is reporting this. Try testing on your phones mobile network maybe?

**Comment by Miodec** [comment]
Any updates?

**Comment by b3nj5m1n** [comment]
I haven't been using the site a lot in the past 2 weeks, but the issue seems to have mostly disappeared, at least for me.

**Comment by Miodec** [comment]
Ill close this for now. Let me know if the issue returns.

**Comment by b3nj5m1n** [comment]
It would also be good to know if @Pinche-Dev is still experiencing this issue.
