### ISSUE TITLE
Allow some tags to have separate Personal Bests

### ISSUE THREAD

**Issue by Miodec** [Miodec/monkeytype#366]

**Comment by jeffalexander** [comment]
I would like to +1 this idea.

Here is my use case. I’m actively learning Colemak and use monkeytype for my practice sessions. I also want to keep my QWERTY skills so every so often I practice QWERTY. I tag these sessions with a 'qwerty' tag.

Because my QWERTY wpm is much higher, I now no longer get to see my Colemak personal bests.

A variation of this feature request could perhaps be to create a config like "exclude these tags from Personal Bests".
