### ISSUE TITLE
Multilanguage TTS

### ISSUE THREAD

**Issue by kolyu7771** [Miodec/monkeytype#397]
Obviously English is the main language, and that's the reason that the Text-To-Speech is English, but since there are other languages supported on the site it would be nice if you started adding other TTS voices for other languages. Since other languages have different pronunciations for other words, it would help a lot people like me (I'm Italian) that like to play around with the other modes, but are forced to use English to actually understand words instead of guessing the words that we're writing in our own language because of the pronunciation of the TTS.

**Comment by Miodec** [comment]
Its hard to work with tts because I think its system dependent. I tried changing the voice of it and some users reported it sounding german even if it was set to English. So I'm not sure if that will be looked into at this time. Unless someone wants to do some research about how this actually works.
