### ISSUE TITLE
Result chart looking weird...

### ISSUE THREAD

**Issue by pingshunhuangalex** [Miodec/monkeytype#586]
Not sure if it's possible to have 0 for wpm while raw oned are showing some values
![image](https://user-images.githubusercontent.com/17170199/99145682-e5749380-26c4-11eb-8af4-a152eb05e655.png)

There was also a time when wpm has some values but raw ones suddenly dropped to some really small value which falls out of the chart and makes things look like the chart has been cut off... (Didn't get a screenshot for that, but got one example when chart got cut off on the raw data)
![image](https://user-images.githubusercontent.com/17170199/99146748-f32f1680-26ce-11eb-9b4f-dedfc0e22bcd.png)

**Comment by Miodec** [comment]
The first screenshot: This will happen if you didn't type any correct words in those seconds. Raw will still be high because it only measures the speed at which you press keys (no matter if they are correct or not).

Second screenshot: If you have `start graphs at zero` disabled, the graph will be fitted to the **wpm** line. This means that the raw line can be cut off sometimes.  The raw drop is there most likely because you slowed down, or stopped completely.
