### ISSUE TITLE
Idea on graphs

### ISSUE THREAD

**Issue by TheeKevin** [Miodec/monkeytype#664]
So on the typing graph basically anything over 250 tests makes the graph extremely cluttered and has points overlap each other so an Idea I have to counter this is to have a feature where the graph would be extremely long so you can scroll through the graph rather than seeing all the points on the graph at once. Perhaps similar to aoeu's typing test graph that shows the average of each wpm on it's typing test. 

I do want this to be a toggleable feature as some people like the cluttered graph and would dislike having to scroll through the entire graph.

**Comment by Miodec** [comment]
Seems difficult to implement for something minor. And the scrolling would hide the axis with the numbers. You can make the graph more readable by changing the date scale, to show less results. You can also see your daily average in the lower, 'activity' graph. (the line, not the bars). You can also change the style of the graph to a scatter one, instead of a line which also removed a quite a bit of clutter.

**Comment by TheeKevin** [comment]
Thanks for answering. I see your point with the axis being unseen. I'll take your suggestions and try to use them :D
