### ISSUE TITLE
 input handling basically considers only single characters, needs group handling.

### ISSUE THREAD

**Issue by randomizermk1** [Miodec/monkeytype#845]
It needs groups handling for implementing Korean or Japanese or Chinese needs

**Comment by Miodec** [comment]
Yeah, this is known. Ill close this because there are issues for this already.

**Comment by Rekkonnect** [comment]
What is the issue that's currently open addressing this issue? I had to enable an IME to type in the jp hiragana and katakana languages, and since there's no kanji, relying on the IME is redundant. The website could support typing the characters in romaji using a standard latin character keyboard and automatically convert them to the appropriate glyphs, which could also detect incorrect digraph versions (じゅ/じょ)
